image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  OS: "alpine"
  OS_VARIANT: "3.8"
  REPOSITORY: "${CI_PROJECT_NAMESPACE}/${OS}"

.build_template: &build_definition
  stage: build
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
  script:
    - VARIANT="${OS_VARIANT}-${CI_JOB_NAME}"
    - BASE_IMAGE="${OS}:${OS_VARIANT}"
    - docker pull "${REPOSITORY}:${VARIANT}" || true
    - docker build
        -t "${REPOSITORY}:${VARIANT}"
        --cache-from "${REPOSITORY}:${VARIANT}"
        --build-arg BASE_IMAGE="${BASE_IMAGE}"
        "${CI_JOB_NAME}/"
    - if [ "${DEFAULT}" = 'true' ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:${CI_JOB_NAME}";
      fi
    - if [ "${LATEST}" = 'true' ]; then
        docker tag "${REPOSITORY}:${VARIANT}" "${REPOSITORY}:latest";
      fi
    - docker images
    - if [ "${CI_COMMIT_REF_NAME}" = 'master' ]; then
        docker push "${REPOSITORY}";
      fi
  after_script:
    - docker logout

curl:
  variables:
    DEFAULT: "true"
  <<: *build_definition

git:
  variables:
    DEFAULT: "true"
  <<: *build_definition

git-ssh:
  variables:
    DEFAULT: "true"
    LATEST: "true"
  <<: *build_definition
